<?php 
# Code generated by sdkgen
# Generated on 2018-07-11 21:18:13.4339587 +0000 UTC using container gcr.io/repcore-prod/sdkgen:1.8.1rc1
# DO NOT EDIT!

namespace Vendasta\Business\V1\internal;

interface BusinessServiceClientInterface
{ 
    /**
     * Auth wrapper for \Business\V1\BusinessServiceClient::Create
     * @param \Business\V1\CreateRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Business\V1\CreateResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Create(\Business\V1\CreateRequest $req, array $options = []): \Business\V1\CreateResponse;
    
    /**
     * Auth wrapper for \Business\V1\BusinessServiceClient::GetMulti
     * @param \Business\V1\GetMultiRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Business\V1\GetMultiResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetMulti(\Business\V1\GetMultiRequest $req, array $options = []): \Business\V1\GetMultiResponse;
    
    /**
     * Auth wrapper for \Business\V1\BusinessServiceClient::Update
     * @param \Business\V1\UpdateRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Update(\Business\V1\UpdateRequest $req, array $options = []): \Google\Protobuf\GPBEmpty;
    
}
