<?php 
# Code generated by sdkgen
# Generated on 2018-07-11 21:18:13.4332155 +0000 UTC using container gcr.io/repcore-prod/sdkgen:1.8.1rc1
# DO NOT EDIT!

namespace Vendasta\Business\V1\internal;

use Vendasta\Vax\GRPCClient;

class BusinessServiceGRPCClient extends GRPCClient implements BusinessServiceClientInterface
{
    private $client;

    /**
     * Constructor for BusinessServiceGRPCClient
     * @param string $hostname hostname of the service to hit
     * @param string $scope
     * @param bool $secure
     * @param float $default_timeout time in milliseconds
     */
    public function __construct(string $hostname, string $scope, bool $secure = true, float $default_timeout = 10000)
    {
        parent::__construct($hostname, $scope, $secure, $default_timeout);
        $this->client = new \Business\V1\BusinessServiceClient($hostname, $this->getClientOptions());
    }
    
    /**
     * Auth wrapper for \Business\V1\BusinessServiceClient::Create
     * @param \Business\V1\CreateRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Business\V1\CreateResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Create(\Business\V1\CreateRequest $req, array $options = []): \Business\V1\CreateResponse
    {
        return $this->doRequest(
            array($this->client, 'Create'),
            $req,
            $options
        );
    }
    
    /**
     * Auth wrapper for \Business\V1\BusinessServiceClient::GetMulti
     * @param \Business\V1\GetMultiRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Business\V1\GetMultiResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetMulti(\Business\V1\GetMultiRequest $req, array $options = []): \Business\V1\GetMultiResponse
    {
        return $this->doRequest(
            array($this->client, 'GetMulti'),
            $req,
            $options
        );
    }
    
    /**
     * Auth wrapper for \Business\V1\BusinessServiceClient::Update
     * @param \Business\V1\UpdateRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Update(\Business\V1\UpdateRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->doRequest(
            array($this->client, 'Update'),
            $req,
            $options
        );
    }
    
}
